export default function LoginContainer({ children, image }) {
  return (
    <div className="bg-white relative lg:pt-14 h-full">
      <div
        className="flex flex-col items-center justify-between pt-0 px-5 md:px-5 pb-0  mt-0 mr-auto mb-0 ml-auto max-w-7xl
xl:px-5 lg:flex-row overflow-x-clip"
      >
        <div className="flex flex-col items-center w-full pt-5 md:px-10  lg:pt-1 lg:flex-row">
          <div className="hidden md:flex w-full h-full bg-cover relative max-w-md lg:max-w-2xl lg:w-1/2">
            <div className="flex flex-col items-center justify-center w-full h-full relative lg:pr-10">
              <img
                alt="login-img"
                src={image}
                className="flex w-full object-cover h-[50vh] p-0"
              />
            </div>
          </div>
          <div className="w-full flex items-center mx-0  relative z-10 max-w-2xl lg:mt-0 lg:w-1/2">
            <div
              className="flex w-full flex-col items-start h-[80vh] md:h-[80vh] justify-start p-5 lg:p-10 bg-white shadow-2xl rounded-xl
    relative z-10"
            >
              <p className="w-full text-2xl xl:text-4xl font-medium text-center leading-snug relative">
                Sign in to our platform
              </p>
              {children}
            </div>
            <svg
              viewBox="0 0 91 91"
              className="absolute top-0 left-0 z-0 w-32 h-32 -mt-12 -ml-12 text-yellow-300
    fill-current"
            >
              <g
                stroke="none"
                strokeWidth="1"
                fillRule="evenodd"
              >
                <g fillRule="nonzero">
                  <g>
                    <g>
                      <circle
                        cx="3.261"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.445"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.445"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 12)">
                      <circle
                        cx="3.261"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.525"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.525"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 24)">
                      <circle
                        cx="3.261"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.605"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.605"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 36)">
                      <circle
                        cx="3.261"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.686"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.686"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 49)">
                      <circle
                        cx="3.261"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="2.767"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="2.767"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 61)">
                      <circle
                        cx="3.261"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="2.846"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="2.846"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 73)">
                      <circle
                        cx="3.261"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="2.926"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="2.926"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 85)">
                      <circle
                        cx="3.261"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.006"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.006"
                        r="2.719"
                      />
                    </g>
                  </g>
                </g>
              </g>
            </svg>
            <svg
              viewBox="0 0 91 91"
              className="absolute bottom-0 right-0 z-0 w-32 h-32 -mb-12 -mr-12 text-indigo-500
    fill-current"
            >
              <g
                stroke="none"
                strokeWidth="1"
                fillRule="evenodd"
              >
                <g fillRule="nonzero">
                  <g>
                    <g>
                      <circle
                        cx="3.261"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.445"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.445"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.445"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 12)">
                      <circle
                        cx="3.261"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.525"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.525"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.525"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 24)">
                      <circle
                        cx="3.261"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.605"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.605"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.605"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 36)">
                      <circle
                        cx="3.261"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.686"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.686"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.686"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 49)">
                      <circle
                        cx="3.261"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="2.767"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="2.767"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="2.767"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 61)">
                      <circle
                        cx="3.261"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="2.846"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="2.846"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="2.846"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 73)">
                      <circle
                        cx="3.261"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="2.926"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="2.926"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="2.926"
                        r="2.719"
                      />
                    </g>
                    <g transform="translate(0 85)">
                      <circle
                        cx="3.261"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="15.296"
                        cy="3.006"
                        r="2.719"
                      />
                      <circle
                        cx="27.333"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="39.369"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="51.405"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="63.441"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="75.479"
                        cy="3.006"
                        r="2.72"
                      />
                      <circle
                        cx="87.514"
                        cy="3.006"
                        r="2.719"
                      />
                    </g>
                  </g>
                </g>
              </g>
            </svg>
          </div>
        </div>
      </div>
    </div>
  );
}
